

const START_EDIT_ELEMENT: 'EDIT: START_EDIT_ELEMENT' = 'EDIT: START_EDIT_ELEMENT';
const EDIT_ELEMENT_DONE: 'EDIT: EDIT_ELEMENT_DONE' = 'EDIT: EDIT_ELEMENT_DONE';
const START_EDIT_BOARD: 'EDIT: START_EDIT_BOARD' = 'EDIT: START_EDIT_BOARD';
const EDIT_BOARD_DONE: 'EDIT: EDIT_BOARD_DONE' = 'EDIT: EDIT_BOARD_DONE';
const LOAD_CONTAINERS: 'EDIT: LOAD_CONTAINERS' = 'EDIT: LOAD_CONTAINERS';
const LOAD_CONTAINERS_DONE: 'EDIT: LOAD_CONTAINERS_DONE' = 'EDIT: LOAD_CONTAINERS_DONE';
